// <auto-generated />
using System;
using Mar_Azul_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mar_Azul_API.Migrations
{
    [DbContext(typeof(DbContextEditorial))]
    [Migration("20250227023423_usuariosprueba")]
    partial class usuariosprueba
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Articulos", b =>
                {
                    b.Property<int>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArticulo"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArticulo");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            IdArticulo = 1,
                            Contenido = "Contenido completo del artículo de prueba 1",
                            Descripcion = "Descripción del artículo de prueba 1",
                            Estado = "Publicado",
                            FechaPublicacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 1,
                            Nombre = "Artículo de Prueba 1",
                            UrlImagen = ""
                        },
                        new
                        {
                            IdArticulo = 2,
                            Contenido = "Contenido completo del artículo de prueba 2",
                            Descripcion = "Descripción del artículo de prueba 2",
                            Estado = "Publicado",
                            FechaPublicacion = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 2,
                            Nombre = "Artículo de Prueba 2",
                            UrlImagen = ""
                        });
                });

            modelBuilder.Entity("Mar_Azul_API.Models.ArticuloAutor", b =>
                {
                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdArticulo", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ArticuloAutores");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.ArticuloAutorizador", b =>
                {
                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArticulo", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ArticuloAutorizadores");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.ArticuloEtiqueta", b =>
                {
                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdEtiqueta")
                        .HasColumnType("int");

                    b.HasKey("IdArticulo", "IdEtiqueta");

                    b.HasIndex("IdEtiqueta");

                    b.ToTable("ArticuloEtiquetas");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.ArticuloRelacion", b =>
                {
                    b.Property<int>("IdArticuloPrincipal")
                        .HasColumnType("int");

                    b.Property<int>("IdArticuloRelacionado")
                        .HasColumnType("int");

                    b.HasKey("IdArticuloPrincipal", "IdArticuloRelacionado");

                    b.HasIndex("IdArticuloRelacionado");

                    b.ToTable("ArticuloRelacionados");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Categorias", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("IdSeccion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdSeccion");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Artículos de software y programación.",
                            Estado = "A",
                            IdSeccion = 1,
                            Nombre = "Software",
                            UrlImagen = "/imagenes_categorias/software.jpg"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Artículos sobre el espacio y el universo.",
                            Estado = "A",
                            IdSeccion = 2,
                            Nombre = "Astronomía",
                            UrlImagen = "/imagenes_categorias/astronomia.jpg"
                        });
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Etiqueta", b =>
                {
                    b.Property<int>("IdEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtiqueta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEtiqueta");

                    b.ToTable("Etiquetas");

                    b.HasData(
                        new
                        {
                            IdEtiqueta = 1,
                            Estado = "A",
                            Nombre = "Innovación"
                        },
                        new
                        {
                            IdEtiqueta = 2,
                            Estado = "A",
                            Nombre = "Ciencia"
                        });
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Secciones", b =>
                {
                    b.Property<int>("IdSeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeccion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSeccion");

                    b.ToTable("Secciones");

                    b.HasData(
                        new
                        {
                            IdSeccion = 1,
                            Descripcion = "Sección de artículos sobre tecnología.",
                            Estado = "A",
                            ImagenURL = "https://example.com/tecnologia.jpg",
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            IdSeccion = 2,
                            Descripcion = "Sección de artículos sobre ciencia.",
                            Estado = "I",
                            ImagenURL = "https://example.com/ciencia.jpg",
                            Nombre = "Ciencia"
                        });
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EsAutor")
                        .HasColumnType("bit");

                    b.Property<bool>("EsAutorizador")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Restablecer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Clave = "123456",
                            Email = "admin@example.com",
                            EsAutor = false,
                            EsAutorizador = false,
                            Estado = "Activo",
                            Nombre = "Admin",
                            Restablecer = "",
                            Rol = "Administrador"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Clave = "123456",
                            Email = "escritor1@example.com",
                            EsAutor = false,
                            EsAutorizador = false,
                            Estado = "Activo",
                            Nombre = "Escritor1",
                            Restablecer = "",
                            Rol = "Escritor"
                        },
                        new
                        {
                            IdUsuario = 3,
                            Clave = "123456",
                            Email = "autorizador1@example.com",
                            EsAutor = false,
                            EsAutorizador = false,
                            Estado = "Activo",
                            Nombre = "Autorizador1",
                            Restablecer = "",
                            Rol = "Autorizador"
                        });
                });

            modelBuilder.Entity("Articulos", b =>
                {
                    b.HasOne("Mar_Azul_API.Models.Categorias", "Categoria")
                        .WithMany("Articulo")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.ArticuloAutor", b =>
                {
                    b.HasOne("Articulos", "Articulo")
                        .WithMany("ArticuloAutores")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mar_Azul_API.Models.Usuario", "Usuario")
                        .WithMany("ArticuloAutores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.ArticuloAutorizador", b =>
                {
                    b.HasOne("Articulos", "Articulo")
                        .WithMany("ArticuloAutorizadores")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mar_Azul_API.Models.Usuario", "Usuario")
                        .WithMany("ArticuloAutorizadores")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.ArticuloEtiqueta", b =>
                {
                    b.HasOne("Articulos", "Articulo")
                        .WithMany("ArticuloEtiquetas")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mar_Azul_API.Models.Etiqueta", "Etiqueta")
                        .WithMany("ArticuloEtiquetas")
                        .HasForeignKey("IdEtiqueta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.ArticuloRelacion", b =>
                {
                    b.HasOne("Articulos", "ArticuloPrincipal")
                        .WithMany("ArticulosRelacionados")
                        .HasForeignKey("IdArticuloPrincipal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Articulos", "ArticuloRelacionado")
                        .WithMany()
                        .HasForeignKey("IdArticuloRelacionado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticuloPrincipal");

                    b.Navigation("ArticuloRelacionado");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Categorias", b =>
                {
                    b.HasOne("Mar_Azul_API.Models.Secciones", "Seccion")
                        .WithMany("Categoria")
                        .HasForeignKey("IdSeccion");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("Articulos", b =>
                {
                    b.Navigation("ArticuloAutores");

                    b.Navigation("ArticuloAutorizadores");

                    b.Navigation("ArticuloEtiquetas");

                    b.Navigation("ArticulosRelacionados");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Categorias", b =>
                {
                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Etiqueta", b =>
                {
                    b.Navigation("ArticuloEtiquetas");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Secciones", b =>
                {
                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Mar_Azul_API.Models.Usuario", b =>
                {
                    b.Navigation("ArticuloAutores");

                    b.Navigation("ArticuloAutorizadores");
                });
#pragma warning restore 612, 618
        }
    }
}
